'use strict';

const CHANGELOG = [
  {
    version: '7.11.0',
    date: '2026-07-20',
    title: 'Workspace — live status bar + focused pane',
    changes: [
      'A live terminal status bar now sits at the very top whenever terminals are running — visible from any view, showing each pane\'s state (active / idle / limit / exited), its tab and command',
      'Account-limit detection: when an agent hits a rate/usage limit, its pane is flagged "limit" in the bar (heuristic on output)',
      'Click any status chip to jump straight to that pane',
      'Click a pane to focus it (blue border) — launched agents / saved commands now go to THAT pane instead of always the first one',
    ],
  },
  {
    version: '7.10.0',
    date: '2026-07-20',
    title: 'Workspace — save & relaunch layouts',
    changes: [
      'New "Save layout" button snapshots the whole workspace — every tab, its panes, and each pane\'s start command',
      'New "Layouts ▾" menu relaunches a saved workspace in one click: it rebuilds the tabs/panes and auto-runs each command',
      'Saving under an existing name overwrites it (no duplicates); "Manage…" lists and deletes saved layouts',
      'Stored on your machine at ~/.codedash/workspace-layouts.json (mode 0600), not in the browser',
      'Fix: leaving and returning to the Workspace view no longer resets it — tabs, panes and their running shells are kept alive (detached, then re-attached intact)',
    ],
  },
  {
    version: '7.9.0',
    date: '2026-07-20',
    title: 'Workspace — saved start commands',
    changes: [
      'Save your own agent start commands (e.g. a proxied launch: HTTPS_PROXY=… claude --dangerously-skip-permissions) and fire them into any pane from the Launch menu',
      'New "Commands" manager to add / delete saved commands; proxy passwords are masked in the UI',
      'Stored on your machine at ~/.codedash/workspace-commands.json (mode 0600), not in the browser',
    ],
  },
  {
    version: '7.8.0',
    date: '2026-07-20',
    title: 'Workspace — iTerm-like tabs & splits',
    changes: [
      'Workspace now has named tabs (double-click to rename) — organize your terminals like in iTerm',
      'Split each tab into 1–4 panes; every pane is an independent shell',
      'Per-pane "Launch" dropdown types an agent command (Claude Code, Codex, Qwen, OpenCode, Kiro, Gemini) straight into that pane',
      'Background tabs stay alive when you switch away — their shells keep running',
    ],
  },
  {
    version: '7.7.0',
    date: '2026-07-19',
    title: 'Workspace — browser terminal (preview)',
    changes: [
      'New "Workspace" view: a real terminal right in the browser (xterm.js) — run shells and agents without leaving codbash',
      'Optional feature: the core dashboard stays dependency-free; the terminal lazily loads @lydell/node-pty, which ships prebuilt binaries (no compiler / node-gyp needed)',
      'Secured by a per-process token + same-origin check on the WebSocket, so it is safe to run the dashboard in server mode',
      'This is the first step (single pane); splits, reattach across reload, saved commands and per-project workspaces are coming next',
    ],
  },
  {
    version: '7.6.0',
    date: '2026-07-19',
    title: 'Recommended tools',
    changes: [
      'New "Recommended" view: handpicked companion apps that pair well with codbash — Copyosity, ccstatusline, RustDesk, iTerm2',
      'Tick tools you already have; the "installed" state is remembered per browser',
      'The tool list is a simple config array, so new tools are easy to add',
    ],
  },
  {
    version: '7.5.3',
    date: '2026-07-19',
    title: 'Sidebar hover tooltips',
    changes: [
      'Every sidebar item now shows a one-line "what it is & why" tooltip on hover — easier to learn what each view and agent filter does',
      'Tooltips render as a single shared element positioned outside the sidebar, so they are never clipped, and adapt to dark / light / monokai themes',
      'Tooltip text doubles as an aria-label for screen-reader accessibility',
    ],
  },
  {
    version: '7.5.2',
    date: '2026-07-19',
    title: 'Reliable self-update restart',
    changes: [
      'Fix: "Update Now" no longer leaves the server dead after installing the new version — the restart now spawns a fully-detached process instead of an unreliable process.on("exit") handler',
      'Self-update restarter reclaims the same port/host and skips reopening the browser (the existing tab reloads itself)',
      'npm install timeout during self-update raised from 60s to 120s for slower connections',
    ],
  },
  {
    version: '7.5.1',
    date: '2026-05-26',
    title: 'Neuraldeep visual identity + Pi hardening',
    changes: [
      'New brand palette: deeper dark backgrounds (#08090C) + neon green accent (#00FF88)',
      'Inter font + crisper text rendering (antialiased smoothing)',
      'Smooth 180ms theme cross-fade when switching dark / light / monokai',
      'Pi / Oh My Pi: tightened resume-target handling — non-Pi Resume buttons no longer routed through Pi-specific helper, /api/launch only forwards resumeTarget for Pi sessions',
      'CSP relaxed precisely for fonts.googleapis.com / fonts.gstatic.com (no other change)',
    ],
  },
  {
    version: '7.5.0',
    date: '2026-05-25',
    title: 'Five new agents, project launcher, subscriptions',
    changes: [
      'New agents: Qwen Code, GitHub Copilot Chat (VS Code), GitHub Copilot CLI, Pi, Oh My Pi',
      'Project launcher: ▶ New / ⟳ Last buttons, GitHub repo onboarding (clone & add)',
      'Projects view split into Projects (launcher) + History subtabs with per-launch agent picker',
      'Subscriptions management in Analytics → History: track paid plans + API deposits for all agents',
      'Background git fetch worker — auto-refresh connected repos on new chat, manual button, or startup',
      'Sidebar reorganised into collapsible Workspace / Agents / Tools groups + Settings → Sidebar tab',
      'Codex Desktop import dedup: imported Claude sessions no longer appear twice in the dashboard',
      'Codex cache invalidation now watches ~/.codex/sessions for new files (no more restart needed)',
      'Active-session mapping no longer misattributes processes to the wrong session via fallback-latest',
      'Worktrees collapse to main repo; $HOME-as-git-root no longer leaks dotfiles remote onto sessions',
      'Windows: Resume preserves backslash paths via Start-Process -WorkingDirectory; PowerShell launcher hardened',
      'Structured message rendering for Codex and Claude Code session details',
      'Cloud Sync: project paths now remap across machines via git remote',
    ],
  },
  {
    version: '7.2.0',
    date: '2026-04-17',
    title: 'Recap titles, sort toggle, analytics sub-tabs',
    changes: [
      'Claude Code recap (away_summary) shown as session title',
      'Message sort toggle in session drawer (newest first / oldest first)',
      'Detect new sessions in existing project dirs + local-agent-mode',
      'Block bulk delete for filter-hidden sessions',
      'Sub-tabs in Cost Analytics: Overview / Breakdown / History',
    ],
  },
  {
    version: '7.1.0',
    date: '2026-04-16',
    title: 'Kilo agent, Linux focus, WSL support',
    changes: [
      'Kilo CLI agent support (SQLite backend)',
      'Linux: precise terminal focus via WINDOWID',
      'WSL: run codbash from WSL with Windows-host browser UI',
      'WSL: agent homes discovery on Windows',
      'Makefile for easy service management',
      'Running card titles white for better visibility',
    ],
  },
  {
    version: '7.0.0',
    date: '2026-04-10',
    title: 'Codbash — rebrand + Cloud Sync + modular frontend',
    changes: [
      'Renamed from codedash to codbash (npm: codbash-app)',
      'Cloud Sync: sync sessions across machines',
      'Frontend split into modules (analytics, calendar, cloud, detail, heatmap, leaderboard)',
      'Improved session file index and disk caching',
    ],
  },
  {
    version: '6.14.0',
    date: '2026-04-08',
    title: 'Leaderboard + GitHub auth + heartbeat',
    changes: [
      'Global leaderboard at codedash-leaderboard.valeriy.workers.dev',
      'GitHub OAuth Device Flow authentication',
      'Anonymous heartbeat — track active installs',
      'Auto-sync stats every 5 minutes',
      'Multi-device support — stats merge across PCs',
      'Anti-cheat: GitHub token verification, rate limits, sanity checks',
      'Leaderboard tabs: Today / Week / All Time',
    ],
  },
  {
    version: '6.12.0',
    date: '2026-04-08',
    title: 'AI session titles + LLM integration',
    changes: [
      'Generate AI session titles via OpenAI-compatible API',
      'LLM Settings: model, URL, API key configuration',
      'Per-card generate/regenerate button',
      'Bulk "AI Titles" in toolbar',
      'Structured output with XML prompt (MAIN_ROLE/MAIN_GUIDELINES)',
      'Support for reasoning models (content:null handling)',
    ],
  },
  {
    version: '6.9.0',
    date: '2026-04-08',
    title: 'Community PRs: Windows, MCP badges, burn rate, kanban',
    changes: [
      'execFileSync + windowsHide prevents CMD flashing on Windows',
      'MCP and Skill badges on sessions (Claude/Codex/OpenCode)',
      'Burn Rate indicator in Cost Analytics',
      'Kanban-board for Running Sessions',
      'Configurable repo-based session grouping',
    ],
  },
  {
    version: '6.8.0',
    date: '2026-04-08',
    title: 'Resizable detail panel + git info',
    changes: [
      'Drag left edge of detail panel to resize (saved in localStorage)',
      'Git info in detail panel: branch, last commit, remote URL, dirty status',
      'Detail panel widened to 840px',
    ],
  },
  {
    version: '6.6.0',
    date: '2026-04-08',
    title: 'Community fixes: Codex count, card heights, sqlite tabs',
    changes: [
      'Fix Codex session message count in grid/list',
      'Equal-height session cards in grid view',
      'Tab separator for sqlite3 queries (fixes pipes in titles)',
      'Git-repo based project grouping',
      'Subscription service/plan selector in Analytics',
      'claude-ext sessions removed from Cursor filter',
    ],
  },
  {
    version: '6.5.0',
    date: '2026-04-08',
    title: 'Host flag, session names, settings page, calendar',
    changes: [
      '--host flag + CODEDASH_HOST env for remote access',
      'Session names from custom-title (Claude) and session_index.jsonl (Codex)',
      'Dedicated Settings page',
      'Custom calendar date picker with range selection',
    ],
  },
  {
    version: '6.3.0',
    date: '2026-04-07',
    title: 'Performance overhaul',
    changes: [
      'Server-side session cache (10s TTL) — 722ms to 0ms repeat loads',
      'Frontend pagination: 60 cards + "Load more"',
      'pollActiveSessions: skip DOM if unchanged',
      'Hover tooltips removed (fixes tooltip pileup bug)',
      'WSL support: scan Windows-side data dirs + \\r\\n fix',
      'Fix Kiro message count (was hardcoded 0)',
      'Project key regex: /[^a-zA-Z0-9-]/g (fixes underscore paths)',
      'cmux proper Resume/Focus via CMUX_WORKSPACE_ID',
    ],
  },
  {
    version: '6.14.6',
    date: '2026-04-08',
    title: 'Cursor sessions + massive performance boost',
    changes: [
      'Scan 400+ Cursor sessions from globalStorage state.vscdb',
      'Progressive loading: fast sessions first, Cursor vscdb in background',
      'Disk cache for sessions, costs, git roots, daily stats, workspace map',
      'Session file index eliminates 15K+ filesystem calls',
      'Analytics/leaderboard: was hanging 5-10 min, now loads in ~2s',
    ],
  },
  {
    version: '6.0.4',
    date: '2026-04-06',
    title: '5 agents: Cursor + live detection for all',
    changes: [
      'Cursor support: read sessions from ~/.cursor/projects/*/agent-transcripts/',
      'LIVE/WAITING detection for ALL agents (Claude, Codex, Cursor, OpenCode, Kiro)',
      'Open in Cursor button (opens project in Cursor IDE)',
      'Detects Claude Code extension running inside Cursor (claude-vscode entrypoint)',
      'GitHub-style SVG activity heatmap with streak stats and tool breakdown',
      'Smart Cursor project path decoding from filesystem',
    ],
  },
  {
    version: '5.3.0',
    date: '2026-04-06',
    title: 'Kiro CLI support',
    changes: [
      '4 agents: Claude Code, Codex, OpenCode, Kiro CLI',
      'Kiro sessions from SQLite (~/Library/Application Support/kiro-cli/)',
      'Orange badge for Kiro in sidebar filter',
    ],
  },
  {
    version: '5.2.0',
    date: '2026-04-06',
    title: 'Heatmap fix, Agents section, cmux',
    changes: [
      'Fix heatmap: scrollable grid, all months visible',
      'Sidebar: "TOOLS" renamed to "AGENTS"',
      'cmux terminal support with trigger-flash',
    ],
  },
  {
    version: '5.1.0',
    date: '2026-04-05',
    title: 'Bug fixes (#7 #8 #9), cmux focus',
    changes: [
      'Fix: delete dialog showing Install Kiro instead of delete',
      'Fix: analytics respects date range filter',
      'Fix: timeline grid/list toggle working',
      'cmux focus walks full parent process chain',
    ],
  },
  {
    version: '5.0.0',
    date: '2026-04-05',
    title: 'Session handoff between agents',
    changes: [
      'codbash handoff <id> [target] — generate context document',
      'Quick handoff: codbash handoff claude codex',
      'Verbosity levels: minimal, standard, verbose, full',
      'Handoff button in detail panel',
      'Node >= 18',
    ],
  },
  {
    version: '4.2.0',
    date: '2026-04-05',
    title: 'OpenCode support',
    changes: [
      'Read sessions from ~/.local/share/opencode/opencode.db',
      'SQLite parsing via sqlite3 CLI (no Node deps)',
      'Purple badge for OpenCode',
    ],
  },
  {
    version: '4.1.0',
    date: '2026-04-04',
    title: 'In-app Changelog',
    changes: [
      'Changelog view with timeline design',
      '"What\'s new" toast after updates',
    ],
  },
  {
    version: '4.0.0',
    date: '2026-04-04',
    title: 'Cross-agent session conversion',
    changes: [
      'Convert sessions between Claude Code and Codex CLI',
      'CLI: codbash convert <id> claude/codex',
      'Convert button in session detail panel',
      'Atomic writes for safety',
    ],
  },
  {
    version: '3.4.0',
    date: '2026-04-04',
    title: 'CLI search, show, docs',
    changes: [
      'codbash search <query> — full-text search from terminal',
      'codbash show <id> — session details with cost and messages',
      'CLAUDE.md and architecture documentation',
    ],
  },
  {
    version: '3.3.0',
    date: '2026-04-04',
    title: 'Install Agents, author credit',
    changes: [
      'Install Agents section: Claude Code, Codex, Kiro, OpenCode',
      'One-click copy install commands',
      'Author credit in sidebar',
    ],
  },
  {
    version: '3.2.0',
    date: '2026-04-04',
    title: 'Real cost calculation',
    changes: [
      'Real cost from actual token usage (not file size estimates)',
      'Model-specific pricing: Opus, Sonnet, Haiku, Codex, GPT-5',
      'Cache pricing: cache_read 90% discount, cache_create 25% premium',
      'Detail panel shows real cost with model and token breakdown',
    ],
  },
  {
    version: '3.1.0',
    date: '2026-04-04',
    title: 'Running sessions view',
    changes: [
      'New "Running" sidebar view with grid layout',
      'CPU, Memory, PID, Uptime for each active session',
      'Focus, Details, Replay buttons',
      'Recently inactive sessions shown below',
    ],
  },
  {
    version: '3.0.0',
    date: '2026-04-04',
    title: 'Session Replay, Cost Analytics',
    changes: [
      'Session Replay: timeline slider, play/pause, progressive messages',
      'Cost Analytics dashboard: daily chart, project bars, top sessions',
      'Focus Terminal button for active sessions',
    ],
  },
  {
    version: '2.1.0',
    date: '2026-04-04',
    title: 'Animated border on live cards',
    changes: [
      'Conic gradient border spins around LIVE cards',
      'WAITING cards: static border',
      'Pulsing dot + LIVE/WAITING badges',
    ],
  },
  {
    version: '2.0.0',
    date: '2026-04-04',
    title: 'Live session detection',
    changes: [
      'Detect running Claude/Codex processes via PID files',
      'LIVE (green) and WAITING (yellow) badges with pulse animation',
      'CPU%, Memory, PID shown on hover',
      'Polling every 5 seconds',
    ],
  },
  {
    version: '1.9.0',
    date: '2026-04-03',
    title: 'Tags fix, search index, Export/Import UI',
    changes: [
      'Fixed tag dropdown positioning',
      'In-memory search index (263ms build, 60s cache)',
      'Export/Import dialog in sidebar',
      'codbash update/restart/stop commands',
    ],
  },
  {
    version: '1.6.0',
    date: '2026-04-03',
    title: 'Message extraction fix',
    changes: [
      'Fixed message extraction for both Claude and Codex',
      'Hover preview and expand cards working',
      'Version badge in sidebar',
    ],
  },
  {
    version: '1.5.0',
    date: '2026-04-03',
    title: 'Deep search, hover preview, expandable cards',
    changes: [
      'Full-text search across all session messages',
      'Hover tooltip with first 6 messages',
      'Expand cards inline with first 10 messages',
    ],
  },
  {
    version: '1.4.0',
    date: '2026-04-03',
    title: 'Export/Import for PC migration',
    changes: [
      'codbash export — archive all sessions as tar.gz',
      'codbash import — restore on new machine',
    ],
  },
  {
    version: '1.3.0',
    date: '2026-04-03',
    title: 'Trigram fuzzy search',
    changes: [
      'Fuzzy search with trigram scoring',
      'Results ranked by relevance',
    ],
  },
  {
    version: '1.1.0',
    date: '2026-04-03',
    title: 'Grid/List toggle, Codex support',
    changes: [
      'Grid/List layout switcher',
      'Codex session parsing fixed',
      'Project navigation from Projects view',
    ],
  },
  {
    version: '1.0.0',
    date: '2026-04-03',
    title: 'Initial release',
    changes: [
      'Session dashboard with dark theme',
      'Group by project, timeline, activity heatmap',
      'Star, tag, delete sessions',
      'Resume in iTerm2/Terminal.app',
      'Terminal selector, theme switcher',
    ],
  },
];

module.exports = { CHANGELOG };
